name: Code Quality Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code-quality-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: npm i
        run: npm i
      - name: Run Lint
        run: npm run lint
      - name: Run Test
        run: npm run test:coverage
      - name: Report Coverage
        uses: tj-actions/coverage-reporter@v5.1
        with:
          coverage-command: 'npm run test:coverage'
      - name: Run Cypress
        uses: cypress-io/github-action@v6
