name: Code Quality Check

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main


jobs:
  code-quality-workflow:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      # - name: Cache dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.npm
      #     key: npm-${{ hashFiles('package-lock.json') }}
      #     restore-keys: |
      #       npm-${{ hashFiles('package-lock.json') }}
      #       npm-

      # - name: Install dependencies
      #   uses: bahmutov/npm-install@v1
      #   with:
      #     useLockFile: false
      # - name: Install dependencies
      # run: npm ci --ignore-scripts
      # - name: Setup go
      #   uses: actions/setup-go@v3
      #   with:
      #     go-version: '1.20'
      - name: Hash Files For Cache
        uses: seepine/hash-files@v1
        id: get-hash
        with: 
          patterns: |-
            **/package-lock.json
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ./node_modules
          key: npm-${{ steps.get-hash.outputs.hash }}
          restore-keys: |
            npm-${{ steps.get-hash.outputs.hash }}
            npm-
      - name: npm i
        run: npm i
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      # - name: npm list
      #   run: npm list
      # - name: Run Lint
      #   run: npm run lint
      # - uses: jwalton/gh-find-current-pr@v1
      #   id: findPr
      - name: Run Pull Request Test
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install
          test-script: "npm run test:coverage"
          annotations: failed-tests
        if: ${{ github.event_name == 'pull_request' }}

      - name: Run Push Test
        run: npm run test:coverage
        if: ${{ github.event_name == 'push' }}

      # - name: Run Cypress
      #   uses: cypress-io/github-action@v6
